### ISSUE TITLE
getting error in train.py

### ISSUE THREAD

**Issue by Siddhant-K-code** [aildnont/covid-cxr#20]
i am getting this error : 
`class_ids = list(sorted(class_weight.keys()))
AttributeError: 'list' object has no attribute 'keys'
`

pls help me to fix this

**Comment by bvanberl** [comment]
Hi Siddhant,

Thanks for reaching out. Are you sure that you've pulled the latest changes from the master branch? The line of code you've pasted in your question is not included in the latest version of train.py. Let me know if you have any more questions.

~ Blake

**Comment by Siddhant-K-code** [comment]
I run the latest code of train.py but still getting same error. please help 
![image](https://user-images.githubusercontent.com/55068936/79247643-68680e00-7e98-11ea-84f1-f42e6984ad43.png)

**Comment by bvanberl** [comment]
Hi Siddhant,
Are your dependencies consistent with those specified in requirements.txt?

**Comment by Siddhant-K-code** [comment]
yes, all are installed with all path are set.

**Comment by bvanberl** [comment]
It appears that this error results from calling the fir function. Did you check the exact version numbers of your installed dependencies vs those in requirements.txt?

**Comment by Siddhant-K-code** [comment]
I have opencv_python of version 4.1.2.30 
Because the required 4.1.0.25 is not available in pip

**Comment by Siddhant-K-code** [comment]
yes, it is fixed now. it was the problem with opencv_python version . and my opencv version was upgraded coz. of py 3.8 .... python 3.7 is better. & Thanks for helping and creating this amazing project.

**Comment by bvanberl** [comment]
Thanks a lot, Siddhant. Glad you got it working for you!
