### ISSUE TITLE
openCV error

### ISSUE THREAD

**Issue by Parag0506** [aildnont/covid-cxr#33]
while running lime_explain.py I encountered the following error : 
```
Traceback (most recent call last):
  File ".\src\interpretability\lime_explain.py", line 116, in <module>
    explain_xray(lime_dict, i, save_exp=True)                   # Generate explanation for image
  File ".\src\interpretability\lime_explain.py", line 83, in explain_xray
    orig_img = cv2.resize(orig_img, new_dim, interpolation=cv2.INTER_NEAREST)     # Resize image
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

I tried to enclose it into a try-catch block, It skips some images but in subsequent files, the error arises. Like 
`error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'`

**Comment by annahung31** [comment]
Hi, I faced the same problem. May I ask how you solve it? Thanks

**Comment by annahung31** [comment]
Oh I found it. That is caused by the wrong image path.
